---
name: Setup Workflow
description: |
  Composite action that performs common setup tasks including checkout, version detection, and branch extraction.
  This replaces the rw-setup.yaml reusable workflow to improve efficiency by running on the same runner.

outputs:
  current-version:
    description: "The current latest version detected from the git repositories tags, semver format"
    value: ${{ steps.determine-semver.outputs.current-version }}
  current-v-version:
    description: "The current latest version detected from the git repositories tags, prefixed with a v character, semver format"
    value: ${{ steps.determine-semver.outputs.current-v-version }}
  version:
    description: "The incremented version number (e.g. the next version), semver format"
    value: ${{ steps.determine-semver.outputs.version }}
  v-version:
    description: "The incremented version number (e.g. the next version), prefixed with a v character, semver format"
    value: ${{ steps.determine-semver.outputs.v-version }}
  pre-release-label:
    description: "Pre-release label of the incremented version"
    value: ${{ steps.determine-semver.outputs.pre-release-label }}
  branch:
    description: "The current GitHub branch"
    value: ${{ steps.extract_branch.outputs.branch }}

runs:
  using: composite
  steps:
    - name: determine semver
      id: determine-semver
      uses: reecetech/version-increment@2024.10.1
      with:
        use_api: true
        increment: minor

    - name: Extract branch name
      shell: bash
      run: |
        # shellcheck disable=SC2086,SC2001
        {
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "branch is $BRANCH"
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
        }
      id: extract_branch
