---
name: Setup GitHub App Token
description: |
  This action generates a GitHub App token and sets it as an environment variable for subsequent steps.

inputs:
  app_id:
    description: "GitHub App ID"
    required: true
  private_key:
    description: "GitHub App private key"
    required: true
  owner:
    description: "Organization or repository owner"
    required: false

runs:
  using: composite
  steps:
    - name: Generate GitHub App token
      id: app_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: ${{ inputs.owner || github.repository_owner }}

    - name: Set token as environment variable
      shell: bash
      run: echo "GITHUB_TOKEN=${{ steps.app_token.outputs.token }}" >> $GITHUB_ENV
