---
name: Super Linter
description: |
  Composite action that runs GitHub Super Linter with environment file support.
  Loads configuration from .github/super-linter.env if it exists and runs the Super Linter.

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}
  env_file_path:
    description: "Path to the Super Linter environment file"
    required: false
    default: ".github/super-linter.env"
  run_local:
    description: "Override RUN_LOCAL setting"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Load Super Linter environment file
      shell: bash
      run: |
        ENV_FILE="${{ inputs.env_file_path }}"
        if [[ -f "$ENV_FILE" ]]; then
          echo "Loading environment variables from $ENV_FILE"
          # Read the env file and export variables to GITHUB_ENV
          while IFS= read -r line || [[ -n "$line" ]]; do
            # Skip empty lines and comments
            if [[ -n "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
              # Remove any trailing whitespace and export to GITHUB_ENV
              echo "$line" >> $GITHUB_ENV
              echo "Loaded: $line"
            fi
          done < "$ENV_FILE"
        else
          echo "Environment file $ENV_FILE not found, using defaults"
        fi

    - name: Run Super Linter
      uses: super-linter/super-linter/slim@v8
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RUN_LOCAL: ${{ inputs.run_local }}
