---
name: Secret Scanning

on:
  workflow_call:

permissions: read-all

jobs:
  secret-scan:
    name: Secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Confirm correct branch to scan
        run: echo "Preparing to scan branch ${{ github.ref_name }}"

      - name: Perform scan to detect leaked credentials & secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --debug --json --only-verified
